services:
  postgres:
    image: postgres:17
    container_name: order-service-db
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL_DOCKER=${DB_URL_DOCKER}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KAFKA_URL=${KAFKA_URL}
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
    
volumes:
  postgres_data: