spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

auth:
  service:
    url: http://localhost:8082

user:
  service:
    url: http://localhost:8081

jwt:
  secret: c3VwZXJTZWN1cmVTZWNyZXRLZXlGb3JKV1RDb25maWd1cmF0aW9uMTIz