spring: 
  datasource:
    url: ${DB_URL_DOCKER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

jwt:
  secret: c3VwZXJTZWN1cmVTZWNyZXRLZXlGb3JKV1RDb25maWd1cmF0aW9uMTIz