spring: 
  datasource:
    url: ${DB_URL_DOCKER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_URL}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
